### ISSUE TITLE
Connection broken

### ISSUE THREAD

**Issue by mrbgfromv** [MTrab/pyworxcloud#117]
Greetings!

Upon testing version 3.04 I got the following error message:

Traceback (most recent call last):
  File "C:\Users\MrBG\Downloads\pyworxcloud-3.0.4\pyworxcloud-3.0.4\pyworxcloud\utils\requests.py", line 73, in GET
    req.raise_for_status()
  File "C:\Users\MrBG\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.worxlandroid.com/api/v2/product-items?status=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MrBG\Downloads\pyworxcloud-3.0.4\pyworxcloud-3.0.4\test.py", line 19, in <module>
    cloud.connect()
  File "C:\Users\MrBG\Downloads\pyworxcloud-3.0.4\pyworxcloud-3.0.4\pyworxcloud\__init__.py", line 234, in connect
    self._fetch()
  File "C:\Users\MrBG\Downloads\pyworxcloud-3.0.4\pyworxcloud-3.0.4\pyworxcloud\__init__.py", line 496, in _fetch
    self._mowers = self._api.get_mowers()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MrBG\Downloads\pyworxcloud-3.0.4\pyworxcloud-3.0.4\pyworxcloud\api.py", line 102, in get_mowers
    mowers = GET(
             ^^^^
  File "C:\Users\MrBG\Downloads\pyworxcloud-3.0.4\pyworxcloud-3.0.4\pyworxcloud\utils\requests.py", line 79, in GET
    raise AuthorizationError()
pyworxcloud.exceptions.AuthorizationError

Username / Password and manual login verified.

Thank you in advance,

Frank

**Comment by MTrab** [comment]
Guess you haven't authorized before connecting

**Comment by mrbgfromv** [comment]
Mmmh.
I tried setting the three environment variables and analternativly hard coded them into test.py
In both ways setup.py didn't complain about missing credentials.

That should be enough, shouldn't it?

**Comment by sracing** [comment]
I can confirm there is a issue.

Using the scrip pyworxcloud/blob/master/test.py or pyworxcloud/blob/master/test_async.py and by using my credentials:
EMAIL = "notshowing@here.de" # environ["EMAIL"]
PASS = "notdisclosed"                 # environ["PASSWORD"]
TYPE = "worx"                              # environ["TYPE"]

I am getting the same Error message:

`2023-04-02 13:24:58,130 [__init__.py] [__init__] [DEBUG] [153] Initializing EventHandler ...
2023-04-02 13:24:58,131 [__init__.py] [connect] [DEBUG] [233] Fetching basic API data
Traceback (most recent call last):
  File "C:\Users\plane\PycharmProjects\pyworx\venv\Lib\site-packages\pyworxcloud\utils\requests.py", line 73, in GET
    req.raise_for_status()
  File "C:\Users\plane\PycharmProjects\pyworx\venv\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.worxlandroid.com/api/v2/product-items?status=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\plane\AppData\Roaming\JetBrains\PyCharmCE2022.3\scratches\scratch_1.py", line 51, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python\Python_311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python_311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python_311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\plane\AppData\Roaming\JetBrains\PyCharmCE2022.3\scratches\scratch_1.py", line 20, in main
    await async_worx()
  File "C:\Users\plane\AppData\Roaming\JetBrains\PyCharmCE2022.3\scratches\scratch_1.py", line 28, in async_worx
    cloud.connect()
  File "C:\Users\plane\PycharmProjects\pyworx\venv\Lib\site-packages\pyworxcloud\__init__.py", line 234, in connect
    self._fetch()
  File "C:\Users\plane\PycharmProjects\pyworx\venv\Lib\site-packages\pyworxcloud\__init__.py", line 496, in _fetch
    self._mowers = self._api.get_mowers()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\plane\PycharmProjects\pyworx\venv\Lib\site-packages\pyworxcloud\api.py", line 102, in get_mowers
    mowers = GET(
             ^^^^
  File "C:\Users\plane\PycharmProjects\pyworx\venv\Lib\site-packages\pyworxcloud\utils\requests.py", line 79, in GET
    raise AuthorizationError()
pyworxcloud.exceptions.AuthorizationError`

**Comment by MTrab** [comment]
Yeah - as mentioned (somewhere) the test files and documentation isn't up to par with version 3 at the moment.

But a valid connection sequence should be something like this
```
cloud = WorxCloud(email, password, vendor)
cloud.authenticate()
cloud.connect()
```

**Comment by mrbgfromv** [comment]
Yes, that's it!
-> simply a missing line in setup.pi
With a bit of twiddling it is displaying all the relevant data.
Thank you very much!

I would - if I knew how - update setup.py so that it should work for other users as well.

**Comment by MTrab** [comment]
Will be updated when the last few problems are fixed
