### ISSUE TITLE
Connection seems to work, but mqtt exception

### ISSUE THREAD

**Issue by henfri** [MTrab/pyworxcloud#95]
Hello,

I am trying the simple example from the wiki.
```
2022-10-24 11:59:33,957 [__init__.py] [connect] [DEBUG] [222] Fetching basic API data
2022-10-24 11:59:34,458 [__init__.py] [connect] [DEBUG] [224] Done fetching basic API data
2022-10-24 11:59:34,458 [__init__.py] [connect] [DEBUG] [226] Setting up MQTT handler
2022-10-24 11:59:34,459 [__init__.py] [connect] [DEBUG] [241] Done setting up MQTT handler, setting MQTT config.
2022-10-24 11:59:34,459 [__init__.py] [connect] [DEBUG] [267] Done setting MQTT config, fetching certificate.
2022-10-24 11:59:34,831 [__init__.py] [connect] [DEBUG] [271] Done fetching certificate, setting TLS.
2022-10-24 11:59:34,831 [__init__.py] [connect] [DEBUG] [276] Done setting TLS, beginning MQTT connect.
2022-10-24 11:59:34,965 [__init__.py] [connect] [DEBUG] [279] MQTT connect done, starting loop
2022-10-24 11:59:34,966 [__init__.py] [connect] [DEBUG] [282] MQTT loop started
2022-10-24 11:59:34,966 [__init__.py] [connect] [DEBUG] [285] Converting date and time string
2022-10-24 11:59:34,967 [__init__.py] [connect] [DEBUG] [290] Connection tasks all done
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1558, in loop_read
    return self._loop_rc_handle(rc)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2350, in _loop_rc_handle
    self._do_on_disconnect(rc, properties)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3475, in _do_on_disconnect
    on_disconnect(self, self._userdata, rc)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 627, in _on_disconnect
    raise MQTTException(
pyworxcloud.exceptions.MQTTException: Unexpected MQTT disconnect - were you perhaps banned?
2022-10-24 11:59:35,194 [__init__.py] [_decode_data] [DEBUG] [371] Data decoding for M started
2022-10-24 11:59:35,194 [__init__.py] [_decode_data] [DEBUG] [374] Found JSON decoded data: {'id': ...
```

The JSON data seems correct.

What could be the issue?

Best regards,
Hendrik

**Comment by MTrab** [comment]
I must admit that I haven't had the time to keep the wiki up-to-speed with the recent changes required after Positec made breaking changes to the API.

So perhaps something have changed so the examples isn't valid anymore.

And no, cannot promise when the wiki will be updated, as the whole module will be rewritten (again) as I have gained access to the Positec repository with the full documentation and support of their API.

The wiki will not be updated until this rewrite are complete sometime during winter.

**Comment by MTrab** [comment]
I'll close this as alot is happening these days in this module and this might be fixed.
And no - documentation still haven't been updated, still focusing on getting the module stable
